set -g mouse on

bind r source-file ~/.config/tmux/tmux.conf

set -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'C-v' send -X rectangle-toggle
bind-key -T copy-mode-vi 'y' send -X copy-pipe 'xclip -sel clip'

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
unbind Up
unbind Down
unbind Left
unbind Right

bind -r C-h resize-pane -L
bind -r C-j resize-pane -D
bind -r C-k resize-pane -U
bind -r C-l resize-pane -R
unbind C-Up
unbind C-Down
unbind C-Left
unbind C-Right

set -g history-file ~/.tmux_history
set -g history-limit 100000
set -g repeat-time 300
bind '"' split-pane -v -c "#{pane_current_path}"
bind '%' split-pane -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g default-terminal "screen-256color"
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "bg=white fg=black"
set -g status-right "%H:%M %b-%d"

set -g base-index 1
set -g renumber-windows on

